---
apiVersion: v1
kind: Service
metadata:
  name: argo-rollout-service
  namespace: roll
spec:
  selector:
    app: nodeapp-rollout
  ports:
    - protocol: TCP
      port: 80  # Expose on port 80 externally
      targetPort: 3000  # Internal port on the container
  type: ClusterIP
