apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
spec:
  replicas: 1  # You can increase replicas as needed
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: avy1013/nodeapp:52d80202c3c389cd68511b4daf3f39f8ea0063d2
          ports:
            - containerPort: 3000
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: MYSQL_HOST
              value: "mysql" 
            - name: MYSQL_DATABASE
              value: "Manhwa-app"
          imagePullPolicy: Always

