---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp
  ports:
    - protocol: TCP
      port: 80  # Expose on port 80 externally
      targetPort: 3000  # Internal port on the container
  type: LoadBalancer
